#!/usr/bin/env bash
# This script will tell the story of passwd
while IFS=':' read -r username password uid gid useridinfo homedir shell; do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
